### ISSUE TITLE
Includes path string (looks like plugin is bypassed)

### ISSUE THREAD

**Issue by Oikio** [albinotonnina/parcel-plugin-inlinesvg#9]
OS: MacOSX 10.13.4
Node: v10.3.0
Parcel: 1.8.1

Good day, couldn't make plugin work. Require and import resolves with path strings, also tried to run example from this repo, same thing.  
`npm run nexample`:
```html
<body>
  <div id="demo"></div>
  <script src="/example.239abad7.js"></script>
  <span>/chrome.93807089.svg</span>
  <span>[object Object]</span>
  <span>[object Object]</span>
  <span>/edge.42ce3460.svg</span>
  <span>/opera.8281208b.svg</span>
  <span>/explorer.54a685bf.svg</span>
  <span>/dummy.9d98d980.svg</span>


</body>
```

**Comment by mbtts** [comment]
It does appear to be broken with the latest version of `react-svg-inline`.
Downgrading to 2.0.1 fixed the problem for me.
I will debug later to see if I can work out where the incompatibility lies.

**Comment by Oikio** [comment]
Hm... actually I tried example from parcel-plugin-inlinesvg without react, so it didn't help. And example-react I couldn't run because of the error: 
```
🚨  Cannot read property 'rootDir' of undefined
    at new Asset (/Users/oikio/projects/parcel-plugin-inlinesvg/node_modules/parcel-bundler/src/Asset.js:22:47)
    at new InlineSvgAsset (/Users/oikio/projects/parcel-plugin-inlinesvg/lib/asset.js:6:5)
    at Parser.getAsset (/Users/oikio/projects/parcel-plugin-inlinesvg/example-react/node_modules/parcel-bundler/src/Parser.js:81:12)
    at Bundler.getLoadedAsset (/Users/oikio/projects/parcel-plugin-inlinesvg/example-react/node_modules/parcel-bundler/src/Bundler.js:387:29)
    at Bundler.resolveAsset (/Users/oikio/projects/parcel-plugin-inlinesvg/example-react/node_modules/parcel-bundler/src/Bundler.js:379:17)
```
UPD: It happens because `options` are not passed to `InlineSvgAsset` for some reason, will take a close look later if have time.
UPD: I have no idea why it happens and only in react example, but I tried it with npm, not yarn, found out yarnlocks later.

**Comment by bre7** [comment]
I've just stumbled across the same "bug" using a different plugin:

The constructor has changed (pkg was removed https://github.com/parcel-bundler/parcel/commit/2f7be14aa9eea3fa9e8ee61591c001937d9757a1) and as a result, the plugin doesn't work with Parcel 1.9.0+

**Comment by dandv** [comment]
I also got the `rootDir` error - #16
